### ISSUE TITLE
Embed vote.org form in a Stepzilla step

### ISSUE THREAD

**Issue by seanedwards** [IndivisibleSomerville/voteremote.us#7]
The vote.org form should be embedded into a Stepzilla step, so that the user data from local storage can prepopulate all of the vote.org form fields.

**Comment by ryanpaixao** [comment]
I created a [pull request](https://github.com/IndivisibleSomerville/voteremote.us/pull/9) that adds the iframes for the Verify, Register, and Absentee Ballot pages from Vote.org. Verify, and Register's fields get pre-populated. However, the Absentee Ballot's field does not. The string parameter values seem to not be the correct ones for that page. Also, two of the Register parameter values were incorrect (zipcode -> zip_5, cell_phone -> digits).
